CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, name TEXT, email TEXT UNIQUE, pw TEXT);
CREATE TABLE IF NOT EXISTS chats(id INTEGER PRIMARY KEY, user_id INT, title TEXT, created TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY, chat_id INT, role TEXT, content TEXT, created TEXT DEFAULT CURRENT_TIMESTAMP);
